name: Build a release Swift toolchain

on:
  schedule:
    - cron: "10 */1 * * *"

jobs:
  call-workflow-510:
    uses: thebrowsercompany/swift-build/.github/workflows/swift-toolchain-workflow.yml@release/5.10
