name: Build a release Swift toolchain

on:
  workflow_dispatch:
  # Schedule to build a new release toolchain nightly.
  schedule:
    - cron: "10 0 * * */1"

jobs:
  call-workflow-510:
    uses: thebrowsercompany/swift-build/.github/workflows/swift-toolchain.yml@release/5.10
